AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdas_init - SAM Template for multiple Lambda functions with Custom Authorizer

Parameters:
  AuthTokenSecret:
    Type: String
    NoEcho: true
    Description: Secret key for JWT token validation

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: lambda_service
        LOG_LEVEL: INFO
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    Auth:
      DefaultAuthorizer: CustomAuthorizer
      Authorizers:
        CustomAuthorizer:
          FunctionArn: !GetAtt CustomAuthorizerFunction.Arn
          FunctionPayloadType: TOKEN
          Identity:
            Header: Authorization
            ValidationExpression: '^Bearer [-0-9a-zA-Z\._]*$'
            ReauthorizeEvery: 300

Resources:
  # Lambda Layer for common dependencies
  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-dependencies
      Description: Common dependencies for Lambda functions
      ContentUri: layers/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain

  # Custom Authorizer Lambda Function
  CustomAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-custom-authorizer
      CodeUri: src/authorizer/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonDependenciesLayer
      Environment:
        Variables:
          AUTH_TOKEN_SECRET: !Ref AuthTokenSecret
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'execute-api:Invoke'
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*'

  # Hello World Lambda Function
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-hello-world
      CodeUri: src/hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonDependenciesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  # Process Data Lambda Function
  ProcessDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-process-data
      CodeUri: src/process_data/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 60
      Layers:
        - !Ref CommonDependenciesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /process
            Method: post

  # Token Generator Function
  TokenGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-token-generator
      CodeUri: src/token_generator/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonDependenciesLayer
      Environment:
        Variables:
          AUTH_TOKEN_SECRET: !Ref AuthTokenSecret
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /token
            Method: post
            Auth: NONE  # Este endpoint no requiere autorización

Outputs:
  # API Gateway Outputs
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  # Layer Outputs
  CommonDependenciesLayerArn:
    Description: ARN of the common dependencies layer
    Value: !Ref CommonDependenciesLayer
  CommonDependenciesLayerVersion:
    Description: Version of the common dependencies layer
    Value: !Ref CommonDependenciesLayer

  # Function Outputs
  HelloWorldFunctionArn:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  ProcessDataFunctionArn:
    Description: Process Data Lambda Function ARN
    Value: !GetAtt ProcessDataFunction.Arn
  CustomAuthorizerFunctionArn:
    Description: Custom Authorizer Lambda Function ARN
    Value: !GetAtt CustomAuthorizerFunction.Arn
  TokenGeneratorFunctionArn:
    Description: Token Generator Lambda Function ARN
    Value: !GetAtt TokenGeneratorFunction.Arn